[tool.black]
skip-string-normalization = true
line-length = 120
include = '\.pyi?$'

[tool.ruff]
line-length = 120
target-version = "py311"
lint.select = ["ALL"]
exclude = [".venv"]
lint.ignore = ["D100", "D104", "D203", "D213", "RUF002"]

[tool.mypy]
python_version = "3.11"
files = "."
allow_redefinition = true
disallow_incomplete_defs = true
ignore_missing_imports = true
strict_optional = true
warn_return_any = false
warn_unused_configs = true
