name: Deploy

on:
  push:
    branches: [ "master", "feature/ci-cd" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ntrubkin/ds-newcomer-bot:latest

      - name: Send Docker Compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 165.232.74.131
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: "compose.yml"
          target: /opt/ds-newcomer-bot

      - name: Deploy app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 165.232.74.131
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
            cd /opt/ds-newcomer-bot
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
            docker compose pull
            docker compose down
            docker compose up -d
