name: Deploy

on:
  push:
    branches: [ "master", "feature/ci-cd" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        run: root@165.232.74.131 | ${{ secrets.SSH_PASS }}
